spring.application.name=project2
spring.h2.console.enabled=true
spring.h2.console.path=/h2console

spring.datasource.url=jdbc:h2:file:D:/Samrat/Learning/Java/SpringBoot_CS5.0/Projects/FileDB/project2

spring.datasource.username=samratdb
spring.datasource.password=Samrat@123

spring.jpa.hibernate.ddl-auto=update